# Generated by Django 4.1.7 on 2023-02-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pictures/')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
