# Generated by Django 4.1.7 on 2023-02-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_doctor_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=50)),
                ('bgroup', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pictures/')),
            ],
        ),
    ]
