# Generated by Django 4.1.6 on 2023-02-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_remove_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
    ]
