# Generated by Django 4.1.6 on 2023-02-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0006_remove_patient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='none', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
