# Generated by Django 4.1.6 on 2023-02-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0007_patient_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
    ]
